<?php

namespace AppBundle\Repository;

/**
 * ShippersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShippersRepository extends \Doctrine\ORM\EntityRepository
{
}
